typedef int MyInt;
// using MyInt = int;
typedef float MyFloat;
// using MyFloat = float;
typedef double MyDouble;
// using MyDouble = double;
typedef bool MyBool;
// using MyBool = bool;
typedef char MyChar;
// using MyChar = char;
